name: hola-mundo
run-name: prueba
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: oracle
          java-version: 17
          java-package: jdk

      - name: Compile and run Java Code
        run: |
          javac Main.java
          java Main
